/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#303033",
        "on-secondary-container": "#bcbbc5",
        "primary-fixed-dim": "#c6c6c7",
        "surface-tint": "#c6c6c7",
        "on-surface-variant": "#c4c7c8",
        "surface-bright": "#3a3939",
        "on-error": "#690005",
        "on-primary": "#2f3131",
        "on-background": "#e5e2e1",
        "surface-dim": "#131313",
        "primary": "#ffffff",
        "secondary-fixed": "#e3e1ec",
        "on-tertiary-container": "#656467",
        "surface-container-low": "#1c1b1b",
        "tertiary-fixed": "#e4e1e5",
        "on-tertiary-fixed-variant": "#47464a",
        "secondary-container": "#4a4b53",
        "secondary": "#c6c5cf",
        "tertiary-fixed-dim": "#c8c6c9",
        "tertiary-container": "#e4e1e5",
        "on-tertiary-fixed": "#1b1b1e",
        "inverse-surface": "#e5e2e1",
        "error-container": "#93000a",
        "on-primary-container": "#636565",
        "surface-container-high": "#2a2a2a",
        "outline": "#8e9192",
        "background": "#131313",
        "outline-variant": "#444748",
        "on-surface": "#e5e2e1",
        "surface-container": "#201f1f",
        "secondary-fixed-dim": "#c6c5cf",
        "primary-fixed": "#e2e2e2",
        "error": "#ffb4ab",
        "on-primary-fixed": "#1a1c1c",
        "on-secondary-fixed": "#1a1b22",
        "on-secondary": "#2f3038",
        "on-primary-fixed-variant": "#454747",
        "tertiary": "#ffffff",
        "surface-container-highest": "#353534",
        "surface": "#131313",
        "surface-variant": "#353534",
        "surface-container-lowest": "#0e0e0e",
        "on-error-container": "#ffdad6",
        "inverse-primary": "#5d5f5f",
        "on-secondary-fixed-variant": "#46464e",
        "primary-container": "#e2e2e2",
        "inverse-on-surface": "#313030"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "body-sm": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "label-code": ["JetBrains Mono", "monospace"],
        "label-caps": ["Geist", "sans-serif"],
        "display": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"]
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-code": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-caps": ["11px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "700" }],
        "display": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "1.6", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
